default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: JPHACKS_development.sqlite3

test:
  <<: *default
  database: JPHACKS_test.sqlite3

production:
  url: <%= ENV['DATABASE_URL'] %>
